### ISSUE TITLE
CL pipeline failure 

### ISSUE THREAD

**Issue by Caroline-99** [Cellular-Semantics/CellMark#9]
<img width="822" alt="image" src="https://github.com/user-attachments/assets/331785d1-bcf5-42cd-8b11-cd97a4037a0e">

**Comment by aleixpuigb** [comment]
We should only add the CL_agreed TRUE, otherwise we might encounter more CL label repetitions.

**Comment by hkir-dev** [comment]
In the [HLCA source file](https://github.com/Cellular-Semantics/CellMark/blob/main/src/markers/HLCA_CellRef_MarkerPerformance_forDOSSource.tsv) there are two clusters annotated as `bronchial goblet cell` and CL_agreed TRUE (line 27 and 29), that seems to be the reason. 

Is this a copy error made by me, should I keep only one of these?

Also, David mentioned: 
> If markers are going into CL there needs to be a single cluster per dataset + the CL mapping could differ from CxG.

**Comment by hkir-dev** [comment]
Sorry, I couldn't understand the solution. Should I make the first one `False`?

|index|cl_class|	cl_label|	Cell_type|	Marker_set|	Minimal_markers|	Minimal_markers_label|	Organ|...|	CL_agreed|
|----|----|----|----|----|----|----|----|----|----|
|27|CL:1000312|	bronchial goblet cell|	Goblet (bronchial)|	CLM:1000026|	ensembl:ENSG00000197943\|ensembl:ENSG00000174501|	PLCG2\|ANKRD36C|	Lung|	...|	True|
|29|CL:1000312|	bronchial goblet cell|	Goblet (subsegmental)|	CLM:1000028|	ensembl:ENSG00000255823\|ensembl:ENSG00000149021|	MTRNR2L8\|SCGB1A1|	Lung|	...|	True|

**Comment by aleixpuigb** [comment]
I think this is because the problem with the PR incorporating commits from a different branch. CLM:1000028 should have remained False.
![image](https://github.com/user-attachments/assets/da58ca71-1ac3-4bad-b9e8-623faaae35ca)

**Comment by hkir-dev** [comment]
resolved by https://github.com/Cellular-Semantics/CellMark/pull/13
